# Site settings
title: Syskall
email: olalonde@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Hi :) I'm Olivier Lalonde, a hacker / startup guy.
   Current interests include JavaScript, Rust, Bitcoin, blockchain and deep learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://syskall.com" # the base hostname & protocol for your site
twitter_username: o_lalonde
github_username: olalonde

highlighter: pygments

permalink: /:title/

# Build settings
markdown: redcarpet

redcarpet:
    extensions: [with_toc_data]

# Twitter share
twitter_tweet_button: true
# Facebook Like
facebook_like: true

# Google Analytics
google_analytics_tracking_id: UA-12888988-1

# Disqus Comments
disqus_short_name: syskall
disqus_show_comment_count: false

gems:
  - jekyll-redirect-from

